.\"     Title: MLVIRSH
.\"    Author: Sylvain Le Gall <gildor@debian.org>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: June 28, 2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "MLVIRSH" "1" "June 28, 2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
mlvirsh \- management user interface for virsh guest domain.
.SH "SYNOPSIS"
.HP 8
\fBmlvirsh\fR [\-c\ \fIURI\fR] [\-r] [[\-help] | [\-\-help]] [\fIcommand\fR]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBmlvirsh\fR
command\&.
.PP
This manual page was written for the Debian GNU/Linux distribution because the original program does not have a manual page\&.
.PP
\fBmlvirsh\fRis an almost complete reimplementation of
\fBvirsh\fR, which is mostly command compatible (there are a very few commands missing, and some commands have a slightly different syntax, but broadly speaking they are equivalent programs except that one is written in C and the other in OCaml)
.PP
\fB\-c \fR\fB\fIURI\fR\fR
.RS 4
Hypervisor connection URI\&.
.RE
.PP
\fB\-r\fR
.RS 4
Read\-only connection\&.
.RE
.PP
\fB\fIcommand\fR\fR
.RS 4
Virsh command\&.
.RE
.PP
\fB\-help\fR, \fB\-\-help\fR
.RS 4
Display an help message\&.
.RE
.SH "COMMANDS"
.PP
There is an extensive list of possible virsh commands\&. You can get a list of it by using the special command
\fBhelp\fR
without arguments\&. Using the same command with another command as argument will give you the help for the command\&.
.PP
\fBattach\-device\fR
.RS 4
Attach device to domain\&.
.RE
.PP
\fBautostart\fR
.RS 4
Set whether a domain autostarts at boot\&.
.RE
.PP
\fBcapabilities\fR
.RS 4
Returns capabilities of hypervisor/driver\&.
.RE
.PP
\fBclose\fR
.RS 4
Close an existing hypervisor connection\&.
.RE
.PP
\fBconnect\fR
.RS 4
Open a new hypervisor connection\&.
.RE
.PP
\fBcreate\fR
.RS 4
Create a domain from an XML file\&.
.RE
.PP
\fBdefine\fR
.RS 4
Define (but don\'t start) a domain from an XML file\&.
.RE
.PP
\fBdetach\-device\fR
.RS 4
Detach device from domain\&.
.RE
.PP
\fBdestroy\fR
.RS 4
Destroy a domain\&.
.RE
.PP
\fBdomblkpeek\fR
.RS 4
Peek into a block device of a domain\&.
.RE
.PP
\fBdomblkstat\fR
.RS 4
Display the block device statistics for a domain\&.
.RE
.PP
\fBdomid\fR
.RS 4
Print the ID of a domain\&.
.RE
.PP
\fBdomifstat\fR
.RS 4
Display the network interface statistics for a domain\&.
.RE
.PP
\fBdominfo\fR
.RS 4
Print the domain info\&.
.RE
.PP
\fBdommaxmem\fR
.RS 4
Print the max memory (in kilobytes) of a domain\&.
.RE
.PP
\fBdommaxvcpus\fR
.RS 4
Print the max VCPUs of a domain\&.
.RE
.PP
\fBdommempeek\fR
.RS 4
Peek into memory of a device\&.
.RE
.PP
\fBdomname\fR
.RS 4
Print the name of a domain\&.
.RE
.PP
\fBdomostype\fR
.RS 4
Print the OS type of a domain\&.
.RE
.PP
\fBdomstate\fR
.RS 4
Print the domain state\&.
.RE
.PP
\fBdomuuid\fR
.RS 4
Print the UUID of a domain\&.
.RE
.PP
\fBdump\fR
.RS 4
Core dump a domain to a file for analysis\&.
.RE
.PP
\fBdumpxml\fR
.RS 4
Print the XML description of a domain\&.
.RE
.PP
\fBfreecell\fR
.RS 4
Display free memory for machine, NUMA cell or range of cells
.RE
.PP
\fBget\-autostart\fR
.RS 4
Print whether a domain autostarts at boot\&.
.RE
.PP
\fBhostname\fR
.RS 4
Print the hostname\&.
.RE
.PP
\fBlist\fR
.RS 4
List the running domains\&.
.RE
.PP
\fBlist\-defined\fR
.RS 4
List the defined but not running domains\&.
.RE
.PP
\fBquit\fR
.RS 4
Quit the interactive terminal\&.
.RE
.PP
\fBmaxvcpus\fR
.RS 4
Print the max VCPUs available\&.
.RE
.PP
\fBnet\-autostart\fR
.RS 4
Set whether a network autostarts at boot\&.
.RE
.PP
\fBnet\-bridgename\fR
.RS 4
Print the bridge name of a network\&.
.RE
.PP
\fBnet\-create\fR
.RS 4
Create a network from an XML file\&.
.RE
.PP
\fBnet\-define\fR
.RS 4
Define (but don\'t start) a network from an XML file\&.
.RE
.PP
\fBnet\-destroy\fR
.RS 4
Destroy a network\&.
.RE
.PP
\fBnet\-dumpxml\fR
.RS 4
Print the XML description of a network\&.
.RE
.PP
\fBnet\-get\-autostart\fR
.RS 4
Print whether a network autostarts at boot\&.
.RE
.PP
\fBnet\-list\fR
.RS 4
List the active networks\&.
.RE
.PP
\fBnet\-list\-defined\fR
.RS 4
List the defined but inactive networks\&.
.RE
.PP
\fBnet\-name\fR
.RS 4
Print the name of a network\&.
.RE
.PP
\fBnet\-start\fR
.RS 4
Start a previously defined inactive network\&.
.RE
.PP
\fBnet\-undefine\fR
.RS 4
Undefine an inactive network\&.
.RE
.PP
\fBnet\-uuid\fR
.RS 4
Print the UUID of a network\&.
.RE
.PP
\fBnodeinfo\fR
.RS 4
Print node information\&.
.RE
.PP
\fBreboot\fR
.RS 4
Reboot a domain\&.
.RE
.PP
\fBrestore\fR
.RS 4
Restore a domain from the named file\&.
.RE
.PP
\fBresume\fR
.RS 4
Resume a domain\&.
.RE
.PP
\fBsave\fR
.RS 4
Save a domain to a file\&.
.RE
.PP
\fBschedparams\fR
.RS 4
Get the current scheduler parameters for a domain\&.
.RE
.PP
\fBschedparamset\fR
.RS 4
Set the scheduler parameters for a domain\&.
.RE
.PP
\fBschedtype\fR
.RS 4
Get the scheduler type\&.
.RE
.PP
\fBsetmem\fR
.RS 4
Set the memory used by the domain (in kilobytes)\&.
.RE
.PP
\fBsetmaxmem\fR
.RS 4
Set the maximum memory used by the domain (in kilobytes)\&.
.RE
.PP
\fBshutdown\fR
.RS 4
Gracefully shutdown a domain\&.
.RE
.PP
\fBstart\fR
.RS 4
Start a previously defined inactive domain\&.
.RE
.PP
\fBsuspend\fR
.RS 4
Suspend a domain\&.
.RE
.PP
\fBtype\fR
.RS 4
Print the driver name
.RE
.PP
\fBundefine\fR
.RS 4
Undefine an inactive domain\&.
.RE
.PP
\fBuri\fR
.RS 4
Print the canonical URI\&.
.RE
.PP
\fBvcpuinfo\fR
.RS 4
Pin domain VCPU to a list of physical CPUs\&.
.RE
.PP
\fBvcpupin\fR
.RS 4
Pin domain VCPU to a list of physical CPUs\&.
.RE
.PP
\fBvcpus\fR
.RS 4
Set the number of virtual CPUs assigned to a domain\&.
.RE
.PP
\fBversion\fR
.RS 4
Print the driver version
.RE
.SH "LICENSE"
.PP
This manual page was written by
Sylvain Le Gall
<gildor@debian\&.org>
for the Debian GNU/Linux system (but may be used by others)\&. Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
Lesser General Public License, Version 2\&.1 or any later version published by the Free Software Foundation; considering as source code all the file that enable the production of this manpage\&.
.SH "AUTHOR"
.PP
\fBSylvain Le Gall\fR <\&gildor@debian\&.org\&>
.sp -1n
.IP "" 4
Author.
.SH "COPYRIGHT"
Copyright \(co 2008 Sylvain Le Gall
.br
